[default.general]
chip = "nRF52840_xxAA"

[default.probe]
protocol = "Swd"
speed = 1000
connect_under_reset = true

[default.flashing]
enabled = true
halt_afterwards = false
restore_unwritten_bytes = false

[default.reset]
enabled = true
halt_afterwards = false

[default.rtt]
enabled = true
timeout = 3000
show_timestamps = false
channels = [
    { up = 0, mode = "String", format = "NoFormat" },
]

[default.rtt.control_block]
address = 0x20000000
